# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc53da442ff5a3a2d5d8e6e7b49f1197509c01ae8800cdcc4200cd0de162bc7ba6d734a6c2ffb044cc6ba698aeb89ae5a32db6163b8d7e2fc1a2ad99be6ee13

test:
  secret_key_base: 3c20cc99495996f6a948ec7235459f6ba325ae0953d79b6bc3d435b007cf58bd2e0b713ab77a1bee2060c40a05f5641ec72519a68f3db6619733a4536af0ed0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
